github: andrea-mariadb, 77ninjamusic, andrea-mariadb-2, andipandi111
patreon: andrea-mariadb
open_collective: andrea_mariadb
ko_fi: 
tidelift: 
community_bridge: 
liberapay: andrea_mariadb
issuehunt: andrea_mariadb
otechie: andrea_mariadb
lfx_crowdfunding: 
custom: 
.npm
.yml
.yaml

